USE master
GO
IF DB_ID(N'BD2_Projekt_OZHID') IS NOT NULL
    DROP DATABASE BD2_Projekt_OZHID;
GO

CREATE DATABASE BD2_Projekt_OZHID
GO

USE [BD2_Projekt_OZHID]
GO

DROP TABLE IF EXISTS dbo.Pracownicy;
GO
CREATE TABLE Pracownicy
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Nazwisko] NVARCHAR(20) NOT NULL,
[Imiê] NVARCHAR(10) NOT NULL,
[Stanowisko] NVARCHAR(40) NOT NULL,
[DataUrodzenia] DATE NOT NULL,
[DataZatrudnienia] DATE NOT NULL,
[Adres] NVARCHAR(60) NOT NULL,
[KodPocztowy] NVARCHAR(10) NOT NULL,
[Miasto] NVARCHAR(40) NOT NULL,
[Kraj] NVARCHAR(20) NOT NULL,
[Telefon] NVARCHAR(25) NOT NULL,
[Uwagi] NVARCHAR(MAX) NULL,
[SZef] INT NULL FOREIGN KEY REFERENCES Pracownicy(ID)
);

DROP TABLE IF EXISTS dbo.Klienci;
GO
CREATE TABLE Klienci
(
[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NazwaFirmy] NVARCHAR(40) NULL,
[Nazwisko] NVARCHAR(20) NOT NULL,
[Imiê] NVARCHAR(10) NOT NULL,
[Adres] NVARCHAR(60) NOT NULL,
[KodPocztowy] NVARCHAR(10) NOT NULL,
[Miasto] NVARCHAR(40) NOT NULL,
[Kraj] NVARCHAR(20) NOT NULL,
[Telefon] NVARCHAR(25) NOT NULL,
);

DROP TABLE IF EXISTS dbo.Spedytorzy;
GO
CREATE TABLE Spedytorzy
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NazwaFirmy] NVARCHAR(40) NOT NULL,
[Telefon]  NVARCHAR(25) NOT NULL,
);

DROP TABLE IF EXISTS dbo.Zamówienia;
GO
CREATE TABLE Zamówienia
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[IdKlienta] INT NOT NULL FOREIGN KEY REFERENCES Klienci(Id),
[IdPracownika] INT NOT NULL FOREIGN KEY REFERENCES Pracownicy(Id),
[DataZamówienia] DATETIME NOT NULL,
[DataWymagana] DATETIME NOT NULL,
[DataWysy³ki] DATETIME NOT NULL,
[IdSpedytora] INT NULL FOREIGN KEY REFERENCES Spedytorzy(Id),
[KosztWysy³ki] MONEY NULL,
[NazwaOdbiorcy] NVARCHAR(40) NOT NULL,
[AdresOdbiorcy] NVARCHAR(60) NOT NULL,
[MiastoOdbiorcy] NVARCHAR(40) NOT NULL,
[KodPocztowyOdbiorcy] NVARCHAR(10) NOT NULL,
[KrajOdbiorcy] NVARCHAR(20) NOT NULL,
);

DROP TABLE IF EXISTS dbo.Dostawcy;
GO
CREATE TABLE Dostawcy
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NazwaFirmy] NVARCHAR(40) NOT NULL,
[Adres] NVARCHAR(60) NOT NULL,
[KodPocztowy] NVARCHAR(10) NOT NULL,
[Miasto] NVARCHAR(40) NOT NULL,
[Kraj] NVARCHAR(20) NOT NULL,
[Telefon] NVARCHAR(25) NOT NULL,
[Strona] NVARCHAR(MAX) NOT NULL,
);

DROP TABLE IF EXISTS dbo.Kategorie;
GO
CREATE TABLE Kategorie
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NazwaKategorii] NVARCHAR(20) NOT NULL,
[Opis]  NVARCHAR(MAX) NULL,
[Grafika] IMAGE NULL
);

DROP TABLE IF EXISTS dbo.Produkty;
GO
CREATE TABLE Produkty
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[NazwaProduktu] NVARCHAR(40) NOT NULL,
[IdKategorii] INT NOT NULL FOREIGN KEY REFERENCES Kategorie(Id),
[IdDostawcy] INT NOT NULL FOREIGN KEY REFERENCES Dostawcy(Id),
[IloœæJednostkowa] SMALLINT NOT NULL,
[CenaJednostkowa] MONEY NOT NULL,
[StanMagazynu] SMALLINT NOT NULL,
[IloœæZamówiona] SMALLINT NULL,
[IloœæMinimum] SMALLINT NOT NULL
);

DROP TABLE IF EXISTS dbo.PozycjeZamówienia;
GO
CREATE TABLE PozycjeZamówienia
(
[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[IdZamówienia] INT NOT NULL FOREIGN KEY  REFERENCES Zamówienia(Id),
[IdProduktu] INT NOT NULL FOREIGN KEY REFERENCES Produkty(Id),
[CenaJednostkowa] MONEY NOT NULL,
[Iloœæ] SMALLINT NOT NULL,
[Rabat] REAL NULL,
);